### ISSUE TITLE
Remove CSS Folder and Files

### ISSUE THREAD

**Issue by rcass** [MisterPeddler/Instanews#2]
Looks like these files are doing nothing, so they can just be deleted.

Woot no need for these while you are using ✨  Sass ✨  atm.

**Comment by MisterPeddler** [comment]
Woopsie!  Consider them gone.  Wiped forever from the face the of the Earth.  Banished to nothing from whence they shall never return.

**Comment by rcass** [comment]
Woot Woot! 👍  💩
